# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/payton/setup-makefiles.sh

LOCAL_SHARED_LIBRARIES := libc++ libc libcutils libdl liblog libm

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),payton)

endif
